# Generated by Django 5.2.4 on 2025-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("staff", "Staff")],
                default="staff",
                max_length=10,
            ),
        ),
    ]
